import os

# Get compiler from pkg-config
compiler = commands.getoutput('pkg-config --variable=compiler dolfin')

# Create a SCons Environment based on the main os environment
env = Environment(ENV=os.environ, CXX=compiler)

# Get compiler flags from pkg-config
env.ParseConfig('pkg-config --cflags --libs dolfin')

env.Program(['primitive_intersection_test.cpp'])
env.Program(['tree_intersection_test.cpp'])
env.Program(['tree_intersection_fail_example.cpp'])
env.Program(['failed_tetrahedron_triangle_intersection.cpp'])
env.Program(['failed_tetrahedron_triangle_intersection_2.cpp'])
